### ISSUE TITLE
Static methods in interface require -target:jvm-1.8

### ISSUE THREAD

**Issue by JWenBin** [tensorflow/java#265] opened 2021-03-31 08:04 UTC
**I can't create any tensor, the error message is：**
Error:(141, 52) Static methods in interface require -target:jvm-1.8
    val fed2 = TInt32.tensorOf( org.tensorflow.ndarray.NdArrays.vectorOf(4, 3, 2, 1) )
Error:(142, 51) Static methods in interface require -target:jvm-1.8
    val fed = TInt32.tensorOf(Shape.of(4)).setInt(4, 0).setInt(3, 1).setInt(2, 2).setInt(1, 3)
Error:(149, 37) Static methods in interface require -target:jvm-1.8
    val itemId_index=TInt32.vectorOf(6135)
........

**my scala code for test is:**
```
    val fed2 = TInt32.tensorOf( org.tensorflow.ndarray.NdArrays.vectorOf(4, 3, 2, 1) )
    val fed = TInt32.tensorOf(Shape.of(4)).setInt(4, 0).setInt(3, 1).setInt(2, 2).setInt(1, 3)
    val a: Array[Int] =Array(1311,1205,1210,0,0,0,0,0,0,0)
    val genres = TInt32.tensorOf(StdArrays.ndCopyOf(a))
    val id_index=TInt32.vectorOf(450)
```

**the version is:** 
```
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow-core-api</artifactId>
            <version>0.3.1</version>
        </dependency>
```

**my environment:**
Windows10 64bit, 
idea 2018.3.5, 
jdk1.8

Thank you!

**Comment by JWenBin** [comment] 2021-03-31 08:32
Infact I don't know what ${javacpp.platform.extension} is, and haven't add this:
```
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow-core-api</artifactId>
  <version>0.3.1</version>
  <classifier>windows-x86_64${javacpp.platform.extension}</classifier>
</dependency>
```

**Comment by JWenBin** [comment] 2021-04-01 02:05
> have

thanks, but my scala(spark) project works well for 2 years without using TF-Java.

**Comment by Craigacp** [comment] 2021-04-01 02:22
If your Scala project wasn't calling any default methods on Java interfaces then it wouldn't have triggered the issue. We use them extensively in TF-Java, and they've been part of Java since Java 8 was released in 2014.

It looks like it found the mkl dependency, as it managed to resolve some of its dependencies. Does Maven give you an error message when building?

**Comment by JWenBin** [comment] 2021-04-01 02:38
I update the last reply just now. when I try to build the project, the error message is the same: 
```
Error:(142, 31) Static methods in interface require -target:jvm-1.8
    val fed2 = TInt32.tensorOf( org.tensorflow.ndarray.NdArrays.vectorOf(4, 3, 2, 1) )
```
And I can build my project correctly without try to create tensor.

**Comment by Craigacp** [comment] 2021-04-01 03:01
> I update the last reply just now. when I try to build the project, the error message is the same:
> 
> ```
> Error:(142, 31) Static methods in interface require -target:jvm-1.8
>     val fed2 = TInt32.tensorOf( org.tensorflow.ndarray.NdArrays.vectorOf(4, 3, 2, 1) )
> ```
> 
> And I can build my project correctly without try to create tensor.
> 
> **I tried a new project, but facing the same error.**

Yes, but the issue is due to your scala build, not a problem in TF-Java. The 1.x version didn't use default methods as heavily, so you didn't hit the issue. The new one does, so you need to make sure that your Scala compiler is happy with using 7 year old language features from Java 8.

**Comment by Craigacp** [comment] 2021-04-01 03:02
I wouldn't expect TF 1.x to be able to load a TF 2 model so that's not too surprising.

**Comment by JWenBin** [comment] 2021-04-01 05:57
> not

yes, I mean this error message only appears while I try to create tensor by using TF-Java 0.3+

> 
> 
> > I update the last reply just now. when I try to build the project, the error message is the same:
> > ```
> > Error:(142, 31) Static methods in interface require -target:jvm-1.8
> >     val fed2 = TInt32.tensorOf( org.tensorflow.ndarray.NdArrays.vectorOf(4, 3, 2, 1) )
> > ```
> > 
> > 
> > And I can build my project correctly without try to create tensor.
> > **I tried a new project, but facing the same error.**
> 
> Yes, but the issue is due to your scala build, not a problem in TF-Java. The 1.x version didn't use default methods as heavily, so you didn't hit the issue. The new one does, so you need to make sure that your Scala compiler is happy with using 7 year old language features from Java 8.

I add '-target:jvm-1.8' to my setting just now:  
![图片](https://user-images.githubusercontent.com/49393828/113238783-05a39880-92dc-11eb-8750-d467e0a6343d.png)

and the error message changed, I can't load my model and create tensor now:
```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.tensorflow.internal.c_api.global.tensorflow.<clinit>(tensorflow.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:48)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:111)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:126)
	at org.tensorflow.RawTensor.<clinit>(RawTensor.java:231)
	at org.tensorflow.Tensor.of(Tensor.java:88)
	at org.tensorflow.Tensor.of(Tensor.java:154)
	at org.tensorflow.Tensor.of(Tensor.java:126)
	at org.tensorflow.types.TInt32.tensorOf(TInt32.java:69)
...
Caused by: java.lang.UnsatisfiedLinkError: no tensorflow_cc in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	... 16 more
```

**Comment by JWenBin** [comment] 2021-04-01 06:09
By the way, I tried to add '<addScalacArgs>-target:jvm-1.8</addScalacArgs>' to my pom.xml first, but it do not work. 
```
<build>
	<plugins>
		<plugin>
			<groupId>org.scala-tools</groupId>
			<artifactId>maven-jar-plugin</artifactId>
			<!--<version>2.3.1</version>-->
			<configuration>
				<archive>
					<manifest>
						<mainClass>my.test.classname</mainClass>
					</manifest>
				</archive>
				<addScalacArgs>-target:jvm-1.8</addScalacArgs>
			</configuration>
		</plugin>
	</plugins>
</build>

```
So I change my IDEA setting instead.

**Closed** 2021-04-01 06:09 UTC
